# Generated by Django 2.2 on 2019-07-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telepone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('description', models.TextField(default='', verbose_name='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serializer_lesson.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serializer_lesson.ProductCategory', verbose_name='')),
            ],
        ),
    ]
