# Generated by Django 2.2 on 2019-07-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telepone',
            new_name='telehpone',
        ),
    ]
